In [5]:
import pandas as pd

In [199]:
df = pd.read_csv('C:\\Users\\vijay\\OneDrive\\Desktop\\Programming\\Datasets\\covid_toy.csv')
df

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [8]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [9]:
df.tail()

    age  gender  fever   cough       city has_covid
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

In [163]:
# Random index dataset
df.sample()

    age  gender  fever cough   city has_covid
38   49  Female  101.0  Mild  Delhi       Yes

In [200]:
df1 = pd.read_csv('C:\\Users\\vijay\\OneDrive\\Desktop\\Programming\\Datasets\\placement.csv')
df

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [165]:
df.head()

   cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1
3  6.88          7.27       1
4  7.52          7.30       1

In [166]:
df.tail()

    cgpa  resume_score  placed
95  6.33          6.38       0
96  8.23          7.76       1
97  6.65          7.78       0
98  8.14          5.63       1
99  6.09          6.61       0

In [167]:
df.sample()

    cgpa  resume_score  placed
29  6.19           7.3       0

In [168]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   cgpa          100 non-null    float64
 1   resume_score  100 non-null    float64
 2   placed        100 non-null    int64
dtypes: float64(2), int64(1)
memory usage: 2.5 KB

In [169]:
df.describe()

           cgpa  resume_score      placed
count  100.0000    100.000000  100.000000
mean     6.9422      6.930500    0.500000
std      1.1192      0.979608    0.502519
min      5.2700      4.950000    0.000000
25%      5.9800      6.190000    0.000000
50%      6.6200      7.055000    0.500000
75%      8.0450      7.640000    1.000000
max      9.4000      9.060000    1.000000

In [180]:
df['age'][0]

60

In [187]:
top_left_corner_df = df.iloc[:4,:3]
top_left_corner_df

   age  gender  fever
0   60    Male  103.0
1   27    Male  100.0
2   42    Male  101.0
3   31  Female   98.0

In [190]:
df1.loc[0:4, ['cgpa', 'placed']]

   cgpa  placed
0  8.14       1
1  6.17       0
2  8.27       1
3  6.88       1
4  7.52       1

In [191]:
p = df.dtypes
p

age            int64
gender        object
fever        float64
cough         object
city          object
has_covid     object
dtype: object

In [194]:
b = df1.empty
b

False

In [217]:
drop1 = df.dropna()
drop1

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[90 rows x 6 columns]

In [218]:
drop1.isnull().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [221]:
dfflipkart = pd.read_csv('C:\\Users\\vijay\\OneDrive\\Desktop\\Programming\\Datasets\\flipkart.csv')
dfflipkart

,Sr. No.,Models,Ratings,Rating No.,Amount of Reviews,RAM,Length,Camera,Battery,Processor,Warranty,Discounted Price,MRP,Off Percentage,Offer check
0,1,"SAMSUNG Galaxy A35 5G (Awesome Iceblue, 128 GB)",4.3,"5,574 Ratings",416 Reviews,8 GB RAM | 128 GB ROM | Expandable Upto 1 TB,16.76 cm (6.6 inch) Full HD+ Display,50MP + 8MP + 5MP | 13MP Front Camera,5000 mAh Battery,Samsung Exynos 1380 Processor,1 Year Manufacturer Warranty for Device and 6 ...,"₹20,999","₹33,999",38% off,Bank Offer
1,2,"SAMSUNG Galaxy F06 5G (Lit Violet, 128 GB)",4.2,"4,020 Ratings",310 Reviews,4 GB RAM | 128 GB ROM | Expandable Upto 1500 GB,17.02 cm (6.7 inch) HD+ Display,50MP + 2MP | 8MP Front Camera,5000 mAh Battery,Dimensity 6300 Processor,1 Year Manufacturer Warranty for Device and 6 ...,"₹8,499","₹13,999",39% off,Bank Offer
2,3,"vivo T4x 5G (Pronto Purple, 128 GB)",4.5,"29,451 Ratings","1,858 Reviews",6 GB RAM | 128 GB ROM,17.07 cm (6.72 inch) Display,50MP + 2MP | 8MP Front Camera,6500 mAh Battery,Dimensity 7300 5G Processor,1 Year Warranty for Device and 6 Months Warran...,"₹13,999","₹17,999",22% off,Bank Offer
3,4,"OnePlus Nord CE4 lite 5G (SUPER SILVER, 128 GB)",4.4,"15,995 Ratings",787 Reviews,8 GB RAM | 128 GB ROM,16.94 cm (6.67 inch) Display,50MP Rear Camera,5500 mAh Battery,1 year,NaN,"₹16,548","₹20,999",21% off,NaN
4,5,"SAMSUNG Galaxy A35 5G (Awesome Iceblue, 256 GB)",4.3,"5,574 Ratings",416 Reviews,8 GB RAM | 256 GB ROM | Expandable Upto 1 TB,16.76 cm (6.6 inch) Full HD+ Display,50MP + 8MP + 5MP | 13MP Front Camera,5000 mAh Battery,Saung Exynos 1380 Processor,1 Year Manufacturer Warranty for Device and 6 ...,"₹22,999","₹36,999",37% off,Bank Offer
5,6,"SAMSUNG Galaxy S24 FE 5G (Blue, 128 GB)",4.4,"1,747 Ratings",151 Reviews,8 GB RAM | 128 GB ROM,17.02 cm (6.7 inch) Full HD+ Display,50MP + 12MP | 10MP Front Camera,4700 mAh Battery,Exynos 2400e Processor,1 Year Manufacturer Warranty for Device and 6 ...,"₹34,999","₹59,999",41% off,Off on Exchange
6,7,"Infinix Note 50s 5G+ (Titanium Grey, 128 GB)",4.6,282 Ratings,37 Reviews,8 GB RAM | 128 GB ROM,17.22 cm (6.78 inch) Full HD+ Display,64MP + 2MP | 13MP Front Camera,5500 mAh Battery,Dimensity 7300 Ultimate Processor,1 Year Warranty for Handset and 6 Months Warra...,"₹15,999","₹21,999",27% off,Bank Offer
7,8,"POCO C75 5G (Enchanted Green, 64 GB)",4.3,"39,014 Ratings","2,113 Reviews",4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,17.48 cm (6.88 inch) HD+ Display,50MP Rear Camera | 5MP Front Camera,5160 mAh Battery,4s Gen 2 5G Processor,1 Year Manufacturer Warranty for Phone and 6 M...,"₹7,699","₹10,999",30% off,Off on Exchange
8,9,"MOTOROLA g35 5G (Midnight Black, 128 GB)",4.2,"38,579 Ratings","3,115 Reviews",4 GB RAM | 128 GB ROM | Expandable Upto 1 TB,17.07 cm (6.72 inch) Full HD+ Display,50MP + 8MP | 16MP Front Camera,5000 mAh Battery,T760 Processor,12 5G Bands with VoNR|4K Video Recording|Visio...,"₹9,999","₹12,499",20% off,Bank Offer
9,10,"SAMSUNG Galaxy F06 5G (Bahama Blue, 128 GB)",4.2,"4,020 Ratings",310 Reviews,4 GB RAM | 128 GB ROM | Expandable Upto 1500 GB,17.02 cm (6.7 inch) HD+ Display,50MP + 2MP | 8MP Front Camera,5000 mAh Battery,Dimensity 6300 Processor,1 Year Manufacturer Warranty for Device and 6 ...,"₹8,499","₹13,999",39% off,Off on Exchange
10,11,"SAMSUNG Galaxy A35 5G (Awesome Lilac, 256 GB)",4.3,"5,574 Ratings",416 Reviews,8 GB RAM | 256 GB ROM | Expandable Upto 1 TB,16.76 cm (6.6 inch) Full HD+ Display,50MP + 8MP + 5MP | 13MP Front Camera,5000 mAh Battery,Exynos 1380 Processor,1 Year Manufacturer Warranty for Device and 6 ...,"₹22,999","₹36,999",37% off,Off on Exchange
11,12,"SAMSUNG Galaxy S24 5G (Marble Gray, 128 GB)",4.5,"1,813 Ratings",176 Reviews,8 GB RAM | 128 GB ROM,15.75 cm (6.2 inch) Full HD+ Display,50MP + 10MP + 12MP | 12MP Front Camera,4000 mAh Battery,Exynos 2400 Processor,1 Year Manufacturer Warranty for Device and 6 ...,"₹54,999","₹74,999",26% off,Bank Offer
12,13,"OnePlus Nord CE4 lite 5G (ULTRA ORANGE, 128 GB)",4.4,"15,995 Ratings",787 Reviews,8 GB RAM | 128 GB ROM,16.94 cm (6.67 inch) Display,50MP Rear Camera,5500 mAh Battery,1 year,NaN,"₹16,482","₹20,999",21% off,NaN
13,14,"POCO C75 5G (Aqua Bliss, 64 GB)",4.3,"39,014 Ratings","2,113 Reviews",4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,17.48 cm (6.88 inch) HD+ Display,50MP Rear Camera | 5MP Front Camera,5160 mAh Battery,4s Gen 2 5G Processor,1 Year Manufacturer Warranty for Phone and 6 M...,"₹7,699","₹10,999",30% off,Off on Exchange
14,15,"REDMI 13 5G (Orchid Pink, 128 GB)",4.3,"31,471 Ratings","1,668 Reviews",6 GB RAM | 128 GB ROM | Expandable Upto 1 TB,17.25 cm (6.79 inch) Full HD+ Display,108MP + 2MP | 13MP Front Camera,5030 mAh Lithium Polymer Battery,4 Gen 2 AE Processor,1 Year Manufacturer Warranty for Phone and 6 M...,"₹12,499","₹17,999",30% off,Bank Offer
15,16,"realme 14x 5G (Crystal Black, 128 GB)",4.3,"6,281 Ratings",320 Reviews,6 GB RAM | 128 GB ROM | Expandable Upto 2 TB,16.94 cm (6.67 inch) HD+ Display,50MP Rear Camera | 8MP Front Camera,6000 mAh Battery,Dimensity 6300 Processor,1 Year Manufacturer Warranty for Device and 6 ...,"₹14,999","₹16,999",11% off,Bank Offer
16,17,"SAMSUNG Galaxy A35 5G (Awesome Navy, 256 GB)",4.3,"5,574 Ratings",416 Reviews,8 GB RAM | 256 GB ROM | Expandable Upto 1 TB,16.76 cm (6.6 inch) Full HD+ Display,50MP + 8MP + 5MP | 13MP Front Camera,5000 mAh Battery,Samsung Exynos 1380 Processor,1 Year Manufacturer Warranty for Device and 6 ...,"₹22,999","₹36,999",37% off,Bank Offer
17,18,"SAMSUNG Galaxy F16 5G (Glam Green, 128 GB)",4.2,363 Ratings,34 Reviews,8 GB RAM | 128 GB ROM,16.91 cm (6.657 inch) Full HD+ Display,50MP + 5MP + 2MP | 13MP Front Camera,5000 mAh Battery,Dimensity 6300 Processor,1 Year Manufacturer Warranty for Device and 6 ...,"₹14,499","₹18,999",23% off,Bank Offer
18,19,"POCO M6 Plus 5G (Graphite Black, 128 GB)",4.2,"37,874 Ratings","2,367 Reviews",6 GB RAM | 128 GB ROM | Expandable Upto 1 TB,17.25 cm (6.79 inch) Full HD+ Display,108MP + 2MP | 13MP Front Camera,5030 mAh Battery,Snapdragon 4 Gen2 AE Processor,1 Year Manufacturer Warranty for Phone and 6 M...,"₹9,999","₹15,999",37% off,Bank Offer
19,20,"Motorola g45 5G (Brilliant Blue, 128 GB)",4.3,"1,43,792 Ratings","7,621 Reviews",8 GB RAM | 128 GB ROM | Expandable Upto 1 TB,16.51 cm (6.5 inch) HD+ Display,50MP + 2MP | 16MP Front Camera,5000 mAh Battery,Snapdragon 6s Gen 3 Processor,1 Year Warranty on Handset and 6 Months Warran...,"₹12,999","₹14,999",13% off,Bank Offer
20,21,"SAMSUNG Galaxy F16 5G (Glam Green, 128 GB)",4.2,539 Ratings,39 Reviews,4 GB RAM | 128 GB ROM,16.91 cm (6.657 inch) Full HD+ Display,50MP + 5MP + 2MP | 13MP Front Camera,5000 mAh Battery,Dimensity 6300 Processor,1 Year Manufacturer Warranty for Device and 6 ...,"₹11,499","₹15,999",28% off,Bank Offer
21,22,"SAMSUNG Galaxy A35 5G (Awesome Lilac, 128 GB)",4.3,"5,574 Ratings",416 Reviews,8 GB RAM | 128 GB ROM | Expandable Upto 1 TB,16.76 cm (6.6 inch) Full HD+ Display,50MP + 8MP + 5MP | 13MP Front Camera,5000 mAh Battery,Samsung Exynos 1380 Processor,1 Year Manufacturer Warranty for Device and 6 ...,"₹20,999","₹33,999",38% off,Bank Offer
22,23,"POCO C75 5G (Silver Stardust, 64 GB)",4.3,"39,014 Ratings","2,113 Reviews",4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,17.48 cm (6.88 inch) HD+ Display,50MP Rear Camera | 5MP Front Camera,5160 mAh Battery,4s Gen 2 5G Processor,1 Year Manufacturer Warranty for Phone and 6 M...,"₹7,699","₹10,999",30% off,Off on Exchange
23,24,"POCO C75 5G (Aqua Bliss, 128 GB)",4.3,"39,014 Ratings","2,113 Reviews",4 GB RAM | 128 GB ROM | Expandable Upto 1 TB,17.48 cm (6.88 inch) HD+ Display,50MP Rear Camera | 5MP Front Camera,5160 mAh Battery,4s Gen 2 5G Processor,1 Year Manufacturer Warranty for Phone and 6 M...,"₹8,499","₹11,499",26% off,NaN

In [222]:
dfflipkart.head()

,Sr. No.,Models,Ratings,Rating No.,Amount of Reviews,RAM,Length,Camera,Battery,Processor,Warranty,Discounted Price,MRP,Off Percentage,Offer check
0,1,"SAMSUNG Galaxy A35 5G (Awesome Iceblue, 128 GB)",4.3,"5,574 Ratings",416 Reviews,8 GB RAM | 128 GB ROM | Expandable Upto 1 TB,16.76 cm (6.6 inch) Full HD+ Display,50MP + 8MP + 5MP | 13MP Front Camera,5000 mAh Battery,Samsung Exynos 1380 Processor,1 Year Manufacturer Warranty for Device and 6 ...,"₹20,999","₹33,999",38% off,Bank Offer
1,2,"SAMSUNG Galaxy F06 5G (Lit Violet, 128 GB)",4.2,"4,020 Ratings",310 Reviews,4 GB RAM | 128 GB ROM | Expandable Upto 1500 GB,17.02 cm (6.7 inch) HD+ Display,50MP + 2MP | 8MP Front Camera,5000 mAh Battery,Dimensity 6300 Processor,1 Year Manufacturer Warranty for Device and 6 ...,"₹8,499","₹13,999",39% off,Bank Offer
2,3,"vivo T4x 5G (Pronto Purple, 128 GB)",4.5,"29,451 Ratings","1,858 Reviews",6 GB RAM | 128 GB ROM,17.07 cm (6.72 inch) Display,50MP + 2MP | 8MP Front Camera,6500 mAh Battery,Dimensity 7300 5G Processor,1 Year Warranty for Device and 6 Months Warran...,"₹13,999","₹17,999",22% off,Bank Offer
3,4,"OnePlus Nord CE4 lite 5G (SUPER SILVER, 128 GB)",4.4,"15,995 Ratings",787 Reviews,8 GB RAM | 128 GB ROM,16.94 cm (6.67 inch) Display,50MP Rear Camera,5500 mAh Battery,1 year,NaN,"₹16,548","₹20,999",21% off,NaN
4,5,"SAMSUNG Galaxy A35 5G (Awesome Iceblue, 256 GB)",4.3,"5,574 Ratings",416 Reviews,8 GB RAM | 256 GB ROM | Expandable Upto 1 TB,16.76 cm (6.6 inch) Full HD+ Display,50MP + 8MP + 5MP | 13MP Front Camera,5000 mAh Battery,Saung Exynos 1380 Processor,1 Year Manufacturer Warranty for Device and 6 ...,"₹22,999","₹36,999",37% off,Bank Offer

In [223]:
df.tail()

    age  gender  fever   cough       city has_covid
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

In [224]:
df.sample()

    age  gender  fever cough    city has_covid
46   19  Female  101.0  Mild  Mumbai        No

In [6]:
df2 = pd.read_csv('C:\\Users\\vijay\\OneDrive\\Desktop\\Programming\\Datasets\\placement.csv')
df2

    cgpa  resume_score  placed
0   8.14          6.52       1
1   6.17          5.17       0
2   8.27          8.86       1
3   6.88          7.27       1
4   7.52          7.30       1
..   ...           ...     ...
95  6.33          6.38       0
96  8.23          7.76       1
97  6.65          7.78       0
98  8.14          5.63       1
99  6.09          6.61       0

[100 rows x 3 columns]

In [7]:
df2.head()

   cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1
3  6.88          7.27       1
4  7.52          7.30       1

In [8]:
df2.tail()

    cgpa  resume_score  placed
95  6.33          6.38       0
96  8.23          7.76       1
97  6.65          7.78       0
98  8.14          5.63       1
99  6.09          6.61       0

In [9]:
df2.sample()

   cgpa  resume_score  placed
4  7.52           7.3       1

In [12]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   cgpa          100 non-null    float64
 1   resume_score  100 non-null    float64
 2   placed        100 non-null    int64
dtypes: float64(2), int64(1)
memory usage: 2.5 KB

In [13]:
df2.describe()

           cgpa  resume_score      placed
count  100.0000    100.000000  100.000000
mean     6.9422      6.930500    0.500000
std      1.1192      0.979608    0.502519
min      5.2700      4.950000    0.000000
25%      5.9800      6.190000    0.000000
50%      6.6200      7.055000    0.500000
75%      8.0450      7.640000    1.000000
max      9.4000      9.060000    1.000000

In [14]:
loc1 = df2.iloc[0:4, 0:3]
loc1

   cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1
3  6.88          7.27       1

In [16]:
iloc1 = df2.iloc[2:4, 1:3]
iloc1

   resume_score  placed
2          8.86       1
3          7.27       1

In [17]:
empty1 = df2.empty
empty1

False

In [20]:
d = df2.size
d

300

In [21]:
a = df2.values
a

array([[8.14, 6.52, 1.  ],
       [6.17, 5.17, 0.  ],
       [8.27, 8.86, 1.  ],
       [6.88, 7.27, 1.  ],
       [7.52, 7.3 , 1.  ],
       [8.77, 6.19, 1.  ],
       [5.34, 7.09, 0.  ],
       [6.56, 6.29, 0.  ],
       [6.32, 6.71, 0.  ],
       [7.69, 7.12, 1.  ],
       [6.18, 6.35, 0.  ],
       [5.44, 6.54, 0.  ],
       [6.09, 7.01, 0.  ],
       [8.5 , 5.09, 1.  ],
       [7.51, 6.25, 1.  ],
       [8.88, 5.93, 1.  ],
       [8.04, 7.64, 1.  ],
       [7.81, 8.71, 1.  ],
       [5.94, 5.88, 0.  ],
       [6.75, 8.11, 1.  ],
       [5.8 , 8.06, 0.  ],
       [6.53, 7.64, 0.  ],
       [6.16, 5.77, 0.  ],
       [6.05, 7.13, 0.  ],
       [8.22, 6.18, 1.  ],
       [7.76, 5.68, 1.  ],
       [6.27, 6.47, 0.  ],
       [5.51, 6.15, 0.  ],
       [7.46, 7.67, 1.  ],
       [6.19, 7.3 , 0.  ],
       [7.36, 7.15, 1.  ],
       [5.92, 7.02, 0.  ],
       [5.87, 7.96, 0.  ],
       [8.43, 7.73, 1.  ],
       [8.87, 7.19, 1.  ],
       [8.07, 7.48, 1.  ],
       [8.16, 7.56, 1.  ],
       [9.05, 8.21, 1.  ],
       [6.  , 8.72, 0.  ],
       [7.5 , 6.19, 1.  ],
       [8.25, 5.32, 1.  ],
       [8.68, 5.15, 1.  ],
       [6.9 , 6.91, 1.  ],
       [8.21, 7.95, 1.  ],
       [5.47, 5.92, 0.  ],
       [8.1 , 5.44, 1.  ],
       [5.83, 5.21, 0.  ],
       [7.05, 8.14, 1.  ],
       [5.54, 6.57, 0.  ],
       [5.46, 6.73, 0.  ],
       [8.22, 6.74, 1.  ],
       [6.54, 7.39, 0.  ],
       [5.9 , 7.5 , 0.  ],
       [6.  , 7.16, 0.  ],
       [5.92, 7.18, 0.  ],
       [6.94, 6.87, 1.  ],
       [6.13, 6.43, 0.  ],
       [6.34, 7.21, 0.  ],
       [6.47, 7.37, 0.  ],
       [5.95, 7.57, 0.  ],
       [5.87, 6.64, 0.  ],
       [6.89, 7.96, 1.  ],
       [5.75, 8.43, 0.  ],
       [8.65, 7.58, 1.  ],
       [7.93, 8.09, 1.  ],
       [6.04, 8.75, 0.  ],
       [8.35, 8.02, 1.  ],
       [6.59, 6.81, 1.  ],
       [6.01, 7.49, 0.  ],
       [8.06, 9.06, 1.  ],
       [7.12, 7.41, 1.  ],
       [7.34, 8.22, 1.  ],
       [7.63, 7.98, 1.  ],
       [5.76, 6.48, 0.  ],
       [5.54, 7.36, 0.  ],
       [6.34, 7.94, 1.  ],
       [9.4 , 5.5 , 1.  ],
       [5.88, 6.92, 0.  ],
       [5.79, 5.66, 0.  ],
       [5.27, 7.28, 0.  ],
       [7.83, 7.7 , 1.  ],
       [6.12, 6.72, 0.  ],
       [7.92, 6.06, 1.  ],
       [7.6 , 8.08, 1.  ],
       [5.76, 6.49, 0.  ],
       [6.72, 5.46, 0.  ],
       [6.18, 5.76, 0.  ],
       [5.62, 5.05, 0.  ],
       [8.07, 6.07, 1.  ],
       [5.99, 7.49, 0.  ],
       [5.85, 5.56, 0.  ],
       [8.28, 6.3 , 1.  ],
       [5.43, 6.18, 0.  ],
       [9.31, 7.39, 1.  ],
       [8.01, 4.95, 1.  ],
       [6.33, 6.38, 0.  ],
       [8.23, 7.76, 1.  ],
       [6.65, 7.78, 0.  ],
       [8.14, 5.63, 1.  ],
       [6.09, 6.61, 0.  ]])

In [23]:
p = df2.sort_values(by = 'resume_score')
p

    cgpa  resume_score  placed
94  8.01          4.95       1
87  5.62          5.05       0
13  8.50          5.09       1
41  8.68          5.15       1
1   6.17          5.17       0
..   ...           ...     ...
17  7.81          8.71       1
38  6.00          8.72       0
65  6.04          8.75       0
2   8.27          8.86       1
69  8.06          9.06       1

[100 rows x 3 columns]

In [25]:
df2['cgpa'] = df2['cgpa'].astype(int)
df2

    cgpa  resume_score  placed
0      8          6.52       1
1      6          5.17       0
2      8          8.86       1
3      6          7.27       1
4      7          7.30       1
..   ...           ...     ...
95     6          6.38       0
96     8          7.76       1
97     6          7.78       0
98     8          5.63       1
99     6          6.61       0

[100 rows x 3 columns]

In [28]:
df2['resume_score'] = df2['resume_score'].astype(int)
df2

    cgpa  resume_score  placed
0      8             6       1
1      6             5       0
2      8             8       1
3      6             7       1
4      7             7       1
..   ...           ...     ...
95     6             6       0
96     8             7       1
97     6             7       0
98     8             5       1
99     6             6       0

[100 rows x 3 columns]

In [29]:
df2['cgpa'] = df2['cgpa'].add(5)
df2['resume_score'] = df2['resume_score'].add(4)
df2['placed'] = df2['placed'].add(6)

In [30]:
df2

    cgpa  resume_score  placed
0     13            10       7
1     11             9       6
2     13            12       7
3     11            11       7
4     12            11       7
..   ...           ...     ...
95    11            10       6
96    13            11       7
97    11            11       6
98    13             9       7
99    11            10       6

[100 rows x 3 columns]

In [32]:
s = df2.count()
s

cgpa            100
resume_score    100
placed          100
dtype: int64

In [33]:
m = df2.max()
m

cgpa            14
resume_score    13
placed           7
dtype: int64

In [35]:
q = df2.min()
q

cgpa            10
resume_score     8
placed           6
dtype: int64

In [36]:
r = df2.mean()
r

cgpa            11.47
resume_score    10.47
placed           6.50
dtype: float64

In [37]:
d = df2.median()
d

cgpa            11.0
resume_score    11.0
placed           6.5
dtype: float64

In [38]:
g = df2.filter(items = ['cgpa', 'resume_score'])
g

    cgpa  resume_score
0     13            10
1     11             9
2     13            12
3     11            11
4     12            11
..   ...           ...
95    11            10
96    13            11
97    11            11
98    13             9
99    11            10

[100 rows x 2 columns]

In [40]:
df2[['cgpa', 'resume_score']]

    cgpa  resume_score
0     13            10
1     11             9
2     13            12
3     11            11
4     12            11
..   ...           ...
95    11            10
96    13            11
97    11            11
98    13             9
99    11            10

[100 rows x 2 columns]

In [41]:
c = df2.filter(items = [5,6], axis = 0)
c

   cgpa  resume_score  placed
5    13            10       7
6    10            11       6

In [42]:
s = df2.to_dict()
s

{'cgpa': {0: 13,
  1: 11,
  2: 13,
  3: 11,
  4: 12,
  5: 13,
  6: 10,
  7: 11,
  8: 11,
  9: 12,
  10: 11,
  11: 10,
  12: 11,
  13: 13,
  14: 12,
  15: 13,
  16: 13,
  17: 12,
  18: 10,
  19: 11,
  20: 10,
  21: 11,
  22: 11,
  23: 11,
  24: 13,
  25: 12,
  26: 11,
  27: 10,
  28: 12,
  29: 11,
  30: 12,
  31: 10,
  32: 10,
  33: 13,
  34: 13,
  35: 13,
  36: 13,
  37: 14,
  38: 11,
  39: 12,
  40: 13,
  41: 13,
  42: 11,
  43: 13,
  44: 10,
  45: 13,
  46: 10,
  47: 12,
  48: 10,
  49: 10,
  50: 13,
  51: 11,
  52: 10,
  53: 11,
  54: 10,
  55: 11,
  56: 11,
  57: 11,
  58: 11,
  59: 10,
  60: 10,
  61: 11,
  62: 10,
  63: 13,
  64: 12,
  65: 11,
  66: 13,
  67: 11,
  68: 11,
  69: 13,
  70: 12,
  71: 12,
  72: 12,
  73: 10,
  74: 10,
  75: 11,
  76: 14,
  77: 10,
  78: 10,
  79: 10,
  80: 12,
  81: 11,
  82: 12,
  83: 12,
  84: 10,
  85: 11,
  86: 11,
  87: 10,
  88: 13,
  89: 10,
  90: 10,
  91: 13,
  92: 10,
  93: 14,
  94: 13,
  95: 11,
  96: 13,
  97: 11,
  98: 13,
  99: 11},
 'resume_score': {0: 10,
  1: 9,
  2: 12,
  3: 11,
  4: 11,
  5: 10,
  6: 11,
  7: 10,
  8: 10,
  9: 11,
  10: 10,
  11: 10,
  12: 11,
  13: 9,
  14: 10,
  15: 9,
  16: 11,
  17: 12,
  18: 9,
  19: 12,
  20: 12,
  21: 11,
  22: 9,
  23: 11,
  24: 10,
  25: 9,
  26: 10,
  27: 10,
  28: 11,
  29: 11,
  30: 11,
  31: 11,
  32: 11,
  33: 11,
  34: 11,
  35: 11,
  36: 11,
  37: 12,
  38: 12,
  39: 10,
  40: 9,
  41: 9,
  42: 10,
  43: 11,
  44: 9,
  45: 9,
  46: 9,
  47: 12,
  48: 10,
  49: 10,
  50: 10,
  51: 11,
  52: 11,
  53: 11,
  54: 11,
  55: 10,
  56: 10,
  57: 11,
  58: 11,
  59: 11,
  60: 10,
  61: 11,
  62: 12,
  63: 11,
  64: 12,
  65: 12,
  66: 12,
  67: 10,
  68: 11,
  69: 13,
  70: 11,
  71: 12,
  72: 11,
  73: 10,
  74: 11,
  75: 11,
  76: 9,
  77: 10,
  78: 9,
  79: 11,
  80: 11,
  81: 10,
  82: 10,
  83: 12,
  84: 10,
  85: 9,
  86: 9,
  87: 9,
  88: 10,
  89: 11,
  90: 9,
  91: 10,
  92: 10,
  93: 11,
  94: 8,
  95: 10,
  96: 11,
  97: 11,
  98: 9,
  99: 10},
 'placed': {0: 7,
  1: 6,
  2: 7,
  3: 7,
  4: 7,
  5: 7,
  6: 6,
  7: 6,
  8: 6,
  9: 7,
  10: 6,
  11: 6,
  12: 6,
  13: 7,
  14: 7,
  15: 7,
  16: 7,
  17: 7,
  18: 6,
  19: 7,
  20: 6,
  21: 6,
  22: 6,
  23: 6,
  24: 7,
  25: 7,
  26: 6,
  27: 6,
  28: 7,
  29: 6,
  30: 7,
  31: 6,
  32: 6,
  33: 7,
  34: 7,
  35: 7,
  36: 7,
  37: 7,
  38: 6,
  39: 7,
  40: 7,
  41: 7,
  42: 7,
  43: 7,
  44: 6,
  45: 7,
  46: 6,
  47: 7,
  48: 6,
  49: 6,
  50: 7,
  51: 6,
  52: 6,
  53: 6,
  54: 6,
  55: 7,
  56: 6,
  57: 6,
  58: 6,
  59: 6,
  60: 6,
  61: 7,
  62: 6,
  63: 7,
  64: 7,
  65: 6,
  66: 7,
  67: 7,
  68: 6,
  69: 7,
  70: 7,
  71: 7,
  72: 7,
  73: 6,
  74: 6,
  75: 7,
  76: 7,
  77: 6,
  78: 6,
  79: 6,
  80: 7,
  81: 6,
  82: 7,
  83: 7,
  84: 6,
  85: 6,
  86: 6,
  87: 6,
  88: 7,
  89: 6,
  90: 6,
  91: 7,
  92: 6,
  93: 7,
  94: 7,
  95: 6,
  96: 7,
  97: 6,
  98: 7,
  99: 6}}

In [44]:
q = df2.to_string()
q

'    cgpa  resume_score  placed\n0     13            10       7\n1     11             9       6\n2     13            12       7\n3     11            11       7\n4     12            11       7\n5     13            10       7\n6     10            11       6\n7     11            10       6\n8     11            10       6\n9     12            11       7\n10    11            10       6\n11    10            10       6\n12    11            11       6\n13    13             9       7\n14    12            10       7\n15    13             9       7\n16    13            11       7\n17    12            12       7\n18    10             9       6\n19    11            12       7\n20    10            12       6\n21    11            11       6\n22    11             9       6\n23    11            11       6\n24    13            10       7\n25    12             9       7\n26    11            10       6\n27    10            10       6\n28    12            11       7\n29    11            11       6\n30    12            11       7\n31    10            11       6\n32    10            11       6\n33    13            11       7\n34    13            11       7\n35    13            11       7\n36    13            11       7\n37    14            12       7\n38    11            12       6\n39    12            10       7\n40    13             9       7\n41    13             9       7\n42    11            10       7\n43    13            11       7\n44    10             9       6\n45    13             9       7\n46    10             9       6\n47    12            12       7\n48    10            10       6\n49    10            10       6\n50    13            10       7\n51    11            11       6\n52    10            11       6\n53    11            11       6\n54    10            11       6\n55    11            10       7\n56    11            10       6\n57    11            11       6\n58    11            11       6\n59    10            11       6\n60    10            10       6\n61    11            11       7\n62    10            12       6\n63    13            11       7\n64    12            12       7\n65    11            12       6\n66    13            12       7\n67    11            10       7\n68    11            11       6\n69    13            13       7\n70    12            11       7\n71    12            12       7\n72    12            11       7\n73    10            10       6\n74    10            11       6\n75    11            11       7\n76    14             9       7\n77    10            10       6\n78    10             9       6\n79    10            11       6\n80    12            11       7\n81    11            10       6\n82    12            10       7\n83    12            12       7\n84    10            10       6\n85    11             9       6\n86    11             9       6\n87    10             9       6\n88    13            10       7\n89    10            11       6\n90    10             9       6\n91    13            10       7\n92    10            10       6\n93    14            11       7\n94    13             8       7\n95    11            10       6\n96    13            11       7\n97    11            11       6\n98    13             9       7\n99    11            10       6'

In [45]:
e = df2.to_csv()
e

',cgpa,resume_score,placed\r\n0,13,10,7\r\n1,11,9,6\r\n2,13,12,7\r\n3,11,11,7\r\n4,12,11,7\r\n5,13,10,7\r\n6,10,11,6\r\n7,11,10,6\r\n8,11,10,6\r\n9,12,11,7\r\n10,11,10,6\r\n11,10,10,6\r\n12,11,11,6\r\n13,13,9,7\r\n14,12,10,7\r\n15,13,9,7\r\n16,13,11,7\r\n17,12,12,7\r\n18,10,9,6\r\n19,11,12,7\r\n20,10,12,6\r\n21,11,11,6\r\n22,11,9,6\r\n23,11,11,6\r\n24,13,10,7\r\n25,12,9,7\r\n26,11,10,6\r\n27,10,10,6\r\n28,12,11,7\r\n29,11,11,6\r\n30,12,11,7\r\n31,10,11,6\r\n32,10,11,6\r\n33,13,11,7\r\n34,13,11,7\r\n35,13,11,7\r\n36,13,11,7\r\n37,14,12,7\r\n38,11,12,6\r\n39,12,10,7\r\n40,13,9,7\r\n41,13,9,7\r\n42,11,10,7\r\n43,13,11,7\r\n44,10,9,6\r\n45,13,9,7\r\n46,10,9,6\r\n47,12,12,7\r\n48,10,10,6\r\n49,10,10,6\r\n50,13,10,7\r\n51,11,11,6\r\n52,10,11,6\r\n53,11,11,6\r\n54,10,11,6\r\n55,11,10,7\r\n56,11,10,6\r\n57,11,11,6\r\n58,11,11,6\r\n59,10,11,6\r\n60,10,10,6\r\n61,11,11,7\r\n62,10,12,6\r\n63,13,11,7\r\n64,12,12,7\r\n65,11,12,6\r\n66,13,12,7\r\n67,11,10,7\r\n68,11,11,6\r\n69,13,13,7\r\n70,12,11,7\r\n71,12,12,7\r\n72,12,11,7\r\n73,10,10,6\r\n74,10,11,6\r\n75,11,11,7\r\n76,14,9,7\r\n77,10,10,6\r\n78,10,9,6\r\n79,10,11,6\r\n80,12,11,7\r\n81,11,10,6\r\n82,12,10,7\r\n83,12,12,7\r\n84,10,10,6\r\n85,11,9,6\r\n86,11,9,6\r\n87,10,9,6\r\n88,13,10,7\r\n89,10,11,6\r\n90,10,9,6\r\n91,13,10,7\r\n92,10,10,6\r\n93,14,11,7\r\n94,13,8,7\r\n95,11,10,6\r\n96,13,11,7\r\n97,11,11,6\r\n98,13,9,7\r\n99,11,10,6\r\n'

In [46]:
idx = df2.columns
idx

Index(['cgpa', 'resume_score', 'placed'], dtype='object')

In [48]:
label = df2.columns[0]
label

'cgpa'

In [50]:
p = df2.columns.tolist()
p

['cgpa', 'resume_score', 'placed']

In [52]:
p = df2.rename(columns = {'cgpa':'updated_cgpa', 'resume_score':'sememster_score'})
p

    updated_cgpa  sememster_score  placed
0             13               10       7
1             11                9       6
2             13               12       7
3             11               11       7
4             12               11       7
..           ...              ...     ...
95            11               10       6
96            13               11       7
97            11               11       6
98            13                9       7
99            11               10       6

[100 rows x 3 columns]

In [53]:
df2['Cgpan'] = df2['cgpa'].astype(int)
df2

    cgpa  resume_score  placed  Cgpan
0     13            10       7     13
1     11             9       6     11
2     13            12       7     13
3     11            11       7     11
4     12            11       7     12
..   ...           ...     ...    ...
95    11            10       6     11
96    13            11       7     13
97    11            11       6     11
98    13             9       7     13
99    11            10       6     11

[100 rows x 4 columns]

In [ ]:
a = df2.drop = ['Cgpan', 'placed']

['Cgpan', 'placed']

In [58]:
df2['new'] = df2['cgpa'].where(df2['cgpa'] > 13, other = 0)
df2.tail(7)

    cgpa  resume_score  placed  Cgpan  new
93    14            11       7     14   14
94    13             8       7     13    0
95    11            10       6     11    0
96    13            11       7     13    0
97    11            11       6     11    0
98    13             9       7     13    0
99    11            10       6     11    0

In [60]:
# notes for df merging, concatenation

# dataframe merging

df1 = pd.DataFrame(
    {
        "A": ["A0", "A1", "A2", "A3"],
        "B": ["B0", "B1", "B2", "B3"],
        "C": ["C0", "C1", "C2", "C3"],
        "D": ["D0", "D1", "D2", "D3"],
    },
    index=[0, 1, 2, 3],
)


df2 = pd.DataFrame(
    {
        "A": ["A4", "A5", "A6", "A7"],
        "B": ["B4", "B5", "B6", "B7"],
        "C": ["C4", "C5", "C6", "C7"],
        "D": ["D4", "D5", "D6", "D7"],
    },
    index=[4, 5, 6, 7],
)


df3 = pd.DataFrame(
    {
        "A": ["A8", "A9", "A10", "A11"],
        "B": ["B8", "B9", "B10", "B11"],
        "C": ["C8", "C9", "C10", "C11"],
        "D": ["D8", "D9", "D10", "D11"],
    },
    index=[8, 9, 10, 11],
)


frames = [df1, df2, df3]

result = pd.concat(frames)
result

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [66]:
data1 = {
    "name": ["Sally", "Mary", "John"],
    "age": [50, 40,30]
}

data2 = {
    "name": ["Sally", "Peter", "Micky"],
    "age": [77, 44, 22]
}

df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

new_df = df1.merge(df2, how = 'right')

In [67]:
new_df

    name  age
0  Sally   77
1  Peter   44
2  Micky   22

In [69]:
# Define a dictionary containing employee data
data1 = {'Name': ['Jai', 'Princi', 'Gaurav', 'Anuj'],
         'Age': [27, 24, 22, 32],
         'Address': ['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
         'Qualification': ['Msc', 'MA', 'MCA', 'Phd']}

# Define a dictionary containing employee data
data2 = {'Name': ['Abhi', 'Ayushi', 'Dhiraj', 'Hitesh'],
         'Age': [17, 14, 12, 52],
         'Address': ['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
         'Qualification': ['Btech', 'B.A.','Bcom','B.hons']}

In [70]:
df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

In [71]:
new_dt = pd.concat([df1, df2])

In [72]:
df = pd.merge(df1, df2, on = 'Address', how = 'inner')
df

   Name_x  Age_x    Address Qualification_x  Name_y  Age_y Qualification_y
0     Jai     27     Nagpur             Msc    Abhi     17           Btech
1  Princi     24     Kanpur              MA  Ayushi     14            B.A.
2  Gaurav     22  Allahabad             MCA  Dhiraj     12            Bcom
3    Anuj     32    Kannuaj             Phd  Hitesh     52          B.hons